import Link from 'next/link'
import { Calculator, ChevronDown, Menu } from 'lucide-react'
import { DemoCalculator } from '@/components/landing/demo-calculator'

const faqs = [
  ['Apakah HPPin gratis digunakan?', 'HPPin dapat mulai digunakan setelah membuat akun. Informasi paket atau batas penggunaan akan selalu ditampilkan secara jelas di dalam aplikasi.'],
  ['Apakah data saya aman?', 'Data setiap usaha dipisahkan berdasarkan akun dan organisasi. Autentikasi dan pembatasan akses database menjaga data antar-pengguna tetap terpisah.'],
  ['Apakah HPPin dapat digunakan dari HP?', 'Ya. Dashboard HPPin responsif dan dapat digunakan melalui browser di HP, tablet, maupun komputer.'],
  ['Apakah laporan dapat diekspor?', 'Ya. Data dan laporan yang tersedia dapat diekspor ke format yang didukung aplikasi.'],
]

export default function LandingPage() {
  return <main className="min-h-screen bg-[#f7faff] text-[#10254a]">
    <header className="sticky top-0 z-40 border-b border-[#dbe5f2] bg-white/95 backdrop-blur-sm">
      <nav className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 lg:px-8">
        <Brand />
        <div className="hidden items-center gap-7 text-sm font-semibold text-[#415676] md:flex">
          <a href="#fitur" className="hover:text-[#185adb]">Fitur</a><a href="#cara-kerja" className="hover:text-[#185adb]">Cara kerja</a><a href="#keunggulan" className="hover:text-[#185adb]">Keunggulan</a><Link href="/donasi" className="hover:text-[#185adb]">Donasi</Link>
        </div>
        <div className="flex items-center gap-2">
          <details className="relative md:hidden"><summary className="grid size-10 cursor-pointer list-none place-items-center rounded-lg border border-[#d4dfed] [&::-webkit-details-marker]:hidden" aria-label="Buka navigasi"><Menu className="size-5" /></summary><div className="absolute right-0 top-12 w-52 rounded-xl border border-[#d4dfed] bg-white p-2 shadow-lg">{[['Fitur','#fitur'],['Cara kerja','#cara-kerja'],['Keunggulan','#keunggulan'],['Donasi','/donasi']].map(([label,href])=><a key={href} href={href} className="block rounded-lg px-3 py-2.5 text-sm font-semibold hover:bg-[#eef4ff]">{label}</a>)}</div></details>
          <Link href="/dashboard" className="inline-flex min-h-10 items-center rounded-lg bg-[#185adb] px-4 text-sm font-bold text-white hover:bg-[#1249ba]">Buka aplikasi</Link>
        </div>
      </nav>
    </header>

    <section className="border-b border-[#dbe5f2] bg-[#f3f7fd]"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-16 lg:grid-cols-[.86fr_1.14fr] lg:px-8 lg:py-24">
      <div className="max-w-xl"><p className="text-sm font-bold tracking-wide text-[#185adb]">Pengelolaan HPP untuk UMKM kuliner</p><h1 className="mt-5 text-4xl font-extrabold leading-[1.1] tracking-[-.035em] text-[#0b1f43] sm:text-5xl lg:text-[58px]">Tahu HPP-nya.<br/>Tahu untungnya.</h1><p className="mt-6 max-w-lg text-lg leading-8 text-[#526581]">Hitung biaya menu, tentukan harga jual, dan jaga profit usaha kuliner dalam satu tempat.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/dashboard" className="inline-flex min-h-12 items-center justify-center rounded-lg bg-[#185adb] px-6 font-bold text-white hover:bg-[#1249ba]">Mulai hitung HPP</Link><a href="#cara-kerja" className="inline-flex min-h-12 items-center justify-center rounded-lg border border-[#b9c9df] bg-white px-6 font-bold text-[#18345f] hover:bg-[#f8fbff]">Lihat cara kerja</a></div></div>
      <ProductDashboard />
    </div></section>

    <DemoCalculator />
    <Features />

    <section id="cara-kerja" className="bg-[#f3f7fd] py-20 lg:py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><p className="text-sm font-bold text-[#185adb]">CARA KERJA</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-.025em] text-[#0b1f43] sm:text-4xl">Tiga langkah, usaha makin cuan</h2><div className="mt-12 grid border-y border-[#cbd8e8] md:grid-cols-3">{[
      ['01','Catat bahan dan harga','Masukkan harga beli, isi kemasan, serta satuan bahan yang kamu gunakan.'],['02','Buat resep dan menu','Susun takaran bahan dan tentukan jumlah porsi dari setiap resep.'],['03','Hitung dan pantau profit','Lihat HPP, food cost, profit, dan margin untuk menentukan harga jual.']
    ].map(([n,t,d],i)=><article key={n} className={`py-8 md:px-8 ${i?'border-t border-[#cbd8e8] md:border-l md:border-t-0':''}`}><p className="text-5xl font-extrabold text-[#aac2e4]">{n}</p><h3 className="mt-7 text-xl font-extrabold text-[#0b1f43]">{t}</h3><p className="mt-3 leading-7 text-[#526581]">{d}</p></article>)}</div></div></section>

    <section className="border-t border-[#dbe5f2] bg-white py-20 lg:py-24"><div className="mx-auto grid max-w-6xl gap-10 px-5 lg:grid-cols-[.75fr_1.25fr] lg:px-8"><div><p className="text-sm font-bold text-[#185adb]">FAQ</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-.025em] text-[#0b1f43] sm:text-4xl">Pertanyaan yang sering ditanyakan</h2><p className="mt-4 leading-7 text-[#526581]">Jawaban singkat sebelum kamu mulai menggunakan HPPin.</p></div><div className="divide-y divide-[#dbe5f2] border-y border-[#dbe5f2]">{faqs.map(([q,a])=><details key={q} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-bold text-[#17345f] [&::-webkit-details-marker]:hidden">{q}<ChevronDown className="size-5 shrink-0 transition group-open:rotate-180"/></summary><p className="pt-4 leading-7 text-[#526581]">{a}</p></details>)}</div></div></section>

    <section className="bg-[#0b2349] px-5 py-16 text-white lg:px-8 lg:py-20"><div className="mx-auto flex max-w-6xl flex-col items-start justify-between gap-8 md:flex-row md:items-center"><div><h2 className="text-3xl font-extrabold tracking-[-.025em] sm:text-4xl">Siap tahu HPP-nya, siap untungnya.</h2><p className="mt-3 text-lg text-[#c6d4e8]">Mulai hitung sekarang dan kendalikan profit usahamu.</p></div><Link href="/dashboard" className="inline-flex min-h-12 shrink-0 items-center rounded-lg bg-white px-6 font-bold text-[#123368] hover:bg-[#eaf1fb]">Mulai hitung HPP</Link></div></section>

    <footer className="border-t border-[#dbe5f2] bg-white py-12"><div className="mx-auto grid max-w-7xl gap-10 px-5 md:grid-cols-[1.4fr_1fr_1fr] lg:px-8"><div className="max-w-sm"><Brand/><p className="mt-3 text-sm leading-6 text-[#526581]">Pengelolaan HPP, food cost, dan profitabilitas untuk usaha kuliner Indonesia.</p></div><FooterGroup title="Produk" links={[['Fitur','#fitur'],['Cara kerja','#cara-kerja'],['Keunggulan','#keunggulan'],['Donasi','/donasi']]}/><div><p className="text-sm font-bold">Informasi</p><div className="mt-4 space-y-3 text-sm text-[#526581]"><span className="block">Kebijakan privasi</span><span className="block">Syarat dan ketentuan</span><a className="block hover:text-[#185adb]" href="mailto:thors622@gmail.com">Kontak</a></div></div></div><div className="mx-auto mt-10 max-w-7xl border-t border-[#e1e8f1] px-5 pt-6 text-xs text-[#6a7b94] lg:px-8">© {new Date().getFullYear()} HPPin.my.id</div></footer>
  </main>
}

function Brand(){return <Link href="/" className="flex items-center gap-2.5 font-extrabold tracking-tight text-[#0c2248]"><span className="grid size-8 place-items-center rounded-lg bg-[#185adb] text-white"><Calculator className="size-4"/></span><span className="text-lg">HPPin<span className="text-[#185adb]">.my.id</span></span></Link>}

function ProductDashboard(){const costs=[['Teh','Rp640'],['Gula','Rp875'],['Cup & sedotan','Rp400'],['Es & air','Rp120']];return <div className="overflow-hidden rounded-[14px] border border-[#cbd8e8] bg-white shadow-[0_18px_50px_rgba(24,55,100,.12)]"><div className="flex items-center justify-between border-b border-[#e1e8f1] px-5 py-4"><div><p className="text-xs font-bold text-[#6a7b94]">RINGKASAN MENU</p><h2 className="mt-1 text-lg font-extrabold">Es Teh Manis</h2></div><span className="rounded-md bg-[#eaf7ee] px-3 py-1.5 text-xs font-bold text-[#19753b]">Sehat</span></div><div className="grid grid-cols-2 border-b border-[#e1e8f1] sm:grid-cols-4">{[['HPP / cup','Rp1.475'],['Harga jual','Rp5.000'],['Food cost','29,5%'],['Profit / cup','Rp3.525']].map(([l,v],i)=><div key={l} className={`p-4 border-[#e1e8f1] ${i%2?'border-l':''} ${i>1?'border-t sm:border-t-0':''} ${i===2?'sm:border-l':''}`}><p className="text-[11px] font-bold uppercase text-[#6a7b94]">{l}</p><p className={`mt-1 text-xl font-extrabold ${l?.includes('Profit')?'text-[#19753b]':''}`}>{v}</p></div>)}</div><div className="grid lg:grid-cols-[1.2fr_.8fr]"><div className="border-b border-[#e1e8f1] p-5 lg:border-b-0 lg:border-r"><div className="flex justify-between"><p className="text-sm font-bold">Tren HPP</p><p className="text-xs text-[#6a7b94]">6 bulan</p></div><svg viewBox="0 0 460 150" className="mt-4 w-full" aria-label="Grafik tren HPP"><path d="M20 125H445M20 75H445" stroke="#e5ebf3"/><path d="M20 105L105 96L190 100L275 78L360 72L445 52V125H20Z" fill="#edf4ff"/><path d="M20 105L105 96L190 100L275 78L360 72L445 52" fill="none" stroke="#185adb" strokeWidth="4"/></svg></div><div className="p-5"><div className="flex justify-between gap-2"><p className="text-sm font-bold">Rincian biaya</p><p className="text-sm font-extrabold text-[#185adb]">Margin 70,5%</p></div><div className="mt-4 divide-y divide-[#e8edf4]">{costs.map(([n,v])=><div key={n} className="flex justify-between py-2.5 text-sm"><span className="text-[#526581]">{n}</span><strong>{v}</strong></div>)}</div></div></div></div>}

function Features(){return <section id="fitur" className="border-y border-[#dbe5f2] bg-white py-20 lg:py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="max-w-3xl"><p className="text-sm font-bold text-[#185adb]">FITUR UTAMA</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-.025em] text-[#0b1f43] sm:text-4xl">Semua angka penting, tanpa spreadsheet yang bikin pusing.</h2><p className="mt-4 text-lg leading-8 text-[#526581]">Satu alur untuk mencatat biaya, menyusun resep, menghitung HPP, dan membaca profit.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-12"><Feature className="bg-[#f7faff] lg:col-span-7" number="01" title="Kelola bahan baku" text="Simpan satuan, isi kemasan, harga beli, dan biaya per unit agar perubahan harga mudah dilacak."><Rows rows={[['Gula pasir','Rp17,5/g'],['Teh','Rp200/g'],['Cup 16 oz','Rp400/pcs']]}/></Feature><Feature className="bg-[#0d2b57] text-white lg:col-span-5" number="02" title="Resep dan menu" text="Susun komposisi resep dan hasil produksi untuk mendapatkan biaya per porsi yang konsisten."><Rows dark rows={[['Teh','6,4 g'],['Gula','100 g'],['Hasil produksi','20 cup']]}/></Feature><Feature className="bg-white lg:col-span-5" number="03" title="HPP otomatis" text="Bahan, kemasan, dan biaya operasional dirangkum menjadi HPP yang mudah diperiksa."><div className="mt-7 border-l-4 border-[#185adb] bg-[#eef4ff] px-5 py-4"><p className="text-xs font-bold text-[#526581]">HPP PER PORSI</p><p className="mt-1 text-3xl font-extrabold">Rp1.475</p></div></Feature><Feature id="keunggulan" className="bg-[#f7faff] lg:col-span-7" number="04" title="Profitabilitas" text="Bandingkan harga jual, food cost, margin, dan profit untuk mengetahui menu yang paling sehat."><div className="mt-7 rounded-xl border border-[#c7ddcf] bg-[#f1faf4] p-5"><p className="text-xs font-bold text-[#426a50]">PROFIT / PORSI</p><p className="mt-1 text-3xl font-extrabold text-[#19753b]">Rp3.525</p><p className="mt-2 text-sm font-bold text-[#19753b]">Margin 70,5%</p></div></Feature></div></div></section>}
function Feature({number,title,text,className,children,id}:{number:string;title:string;text:string;className:string;children:React.ReactNode;id?:string}){return <article id={id} className={`rounded-[14px] border border-[#d8e3f0] p-6 sm:p-8 ${className}`}><p className="text-sm font-bold text-[#5e91e8]">{number}</p><h3 className="mt-3 text-2xl font-extrabold">{title}</h3><p className="mt-3 leading-7 opacity-75">{text}</p>{children}</article>}
function Rows({rows,dark=false}:{rows:string[][];dark?:boolean}){return <div className={`mt-7 overflow-hidden rounded-xl border ${dark?'border-white/20':'border-[#d8e3f0] bg-white'}`}>{rows.map(([n,v])=><div key={n} className={`flex justify-between border-b px-4 py-3 text-sm last:border-0 ${dark?'border-white/15':'border-[#edf1f6]'}`}><span>{n}</span><strong>{v}</strong></div>)}</div>}
function FooterGroup({title,links}:{title:string;links:string[][]}){return <div><p className="text-sm font-bold">{title}</p><div className="mt-4 space-y-3 text-sm text-[#526581]">{links.map(([l,h])=><a key={h} className="block hover:text-[#185adb]" href={h}>{l}</a>)}</div></div>}
