-- Keep the internal limiter table well-formed for maintenance and replication.
alter table private.rate_limits
  add column if not exists id bigint generated by default as identity;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'private.rate_limits'::regclass
      and contype = 'p'
  ) then
    alter table private.rate_limits
      add constraint rate_limits_pkey primary key (id);
  end if;
end;
$$;
